### ISSUE TITLE
handling log-lik loss

### ISSUE THREAD

**Issue by jlstiles** [ecpolley/SuperLearner#101]
It makes sense to use a log-lik loss in the meta-learning fit if the outcome is binary and log-lik was used to create the learner fits, however, this loss is not bounded necessarily so it may be worthwhile to insure the boundedness of the loss and hence the oracle properties of SL by truncation (or an option to do so) of the predictions to say between [0+eps, 1-esp] a priori to the meta-learning step if anyone uses method.NNloglik.  I realize this may be an issue if someone forgets to write a wrapper for a classifier that outputs only 0 and 1 and then has a silly log-likelihood loss, which might break things.

**Comment by ck37** [comment]
This sounds reasonable to me.

**Comment by ecpolley** [comment]
`method.NNloglik` already does this with the `trimLogit` function, with eps controlled by the control$trimLogit parameter.

**Comment by jlstiles** [comment]
Ahh, very well, didn't see that, thanks!

**Comment by ecpolley** [comment]
Yeah, it is currently only used for the predictions, but wasn't incorporated with the individual algorithm CV risk estimate (although I don't recall why). So you can encounter cases where the algorithm has a CV risk estimate (`cvRisk`) of infinity, but a non-zero coefficient because of the trimmed logit function.

**Comment by ck37** [comment]
One thing I just noticed on this - by default trimLogit() will not actually trim the probabilities, because of the way control$trimLogit is passed into the trimLogit function. It always passes in a value, even though that value is NULL if control$trimLogit is not specified, and therefore trimLogit() does not use the function argument default for trim.

One needs to explicitly pass a control list into SuperLearner() that specifies a trimLogit value in order for trimLogit() to do anything. So we should ideally fix this so that SuperLearner is more robust by default.

Here is some sample code:

```{r}
################
# Simulate some data

set.seed(1)
n = 100

y = rbinom(n, 1, 0.1)
table(y)

library_names = c("mean", "learner1", "learner2")

#######
# Version A: two columns and no 0's or 1's
z_a = cbind(mean = mean(y),
            lib1 = rep(runif(n, 0.1, 0.9)),
            lib2 = rep(runif(n, 0.2, 0.8)))

method = SuperLearner::method.NNloglik()
result = method$computeCoef(z_a, y, library_names, obsWeights = rep(1, n),
                   verbose = TRUE, control = list())

# This version works fine, as expected.
result$cvRisk
result$coef
result$optimizer$convergence
result$optimizer$message

#######
# Version B: two columns that have 0's and 1's
z_b = cbind(mean = mean(y),
            lib1 = rep(0, n),
            lib2 = rep(1, n))

# Gives error in optim
result = method$computeCoef(z_b, y, library_names, obsWeights = rep(1, n),
                   verbose = TRUE, control = list())

# Explicitly specifying the default value of trimLogit resolves the issue.
result = method$computeCoef(z_b, y, library_names, obsWeights = rep(1, n),
                   verbose = TRUE, control = list(trimLogit = 0.00001))
result$cvRisk
result$coef

# This shows how the default value of the trim argument in trimLogit() is not
# used due to how we pass in control$trimLogit.

# Doesn't use default value of trim
trimLogit(z_b, list()$trimLogit)

# Doesn't use default value of trim
trimLogit(z_b, NULL)

# Uses default value of trim
trimLogit(z_b)
```

**Comment by ecpolley** [comment]
If you look further up in the `SuperLearner` you will find a value for trimLogit will always be set even if not explicitly defined in the `SuperLearner` arguments. The default value is 0.001. The example below shows it is working. But note this is only for the estimation of the coefficients, the trimmed probabilities aren't saved back to the library.predict matrix.

        library(SuperLearner)
    
    set.seed(1)
    N <- 200
    X <- matrix(rnorm(N*10), N, 10)
    X <- as.data.frame(X)
    Y <- rbinom(N, 1, plogis(.2*X[, 1] + .1*X[, 2] - .2*X[, 3] +
      .1*X[, 3]*X[, 4] - .2*abs(X[, 4])))
    
    SL.always0 <- function (Y, X, newX, family, obsWeights, id, ...) 
    {
    
        pred <- rep(0, nrow(newX))
        fit <- vector("list", length = 0)
        class(fit) <- c("SL.always0")
        out <- list(pred = pred, fit = fit)
        return(out)
    }
    
    SL.library <- c("SL.glm", "SL.always0", "SL.mean")
    set.seed(1)
    test.NNloglik <- SuperLearner(Y = Y, X = X, SL.library = SL.library, method = "method.NNloglik", family = binomial(), cvControl = list(shuffle = FALSE))
    test.NNloglik
    test.NNloglik$control  # shows default value of 0.001
    
    set.seed(1)
    test.NNloglik2 <- SuperLearner(Y = Y, X = X, SL.library = SL.library, method = "method.NNloglik", family = binomial(), control = list(saveFitLibrary = FALSE), cvControl = list(shuffle = FALSE))
    test.NNloglik2
    test.NNloglik2$control  # shows default value of 0.001
    
    set.seed(1)
    test.NNloglik3 <- SuperLearner(Y = Y, X = X, SL.library = SL.library, method = "method.NNloglik", family = binomial(), control = list(saveFitLibrary = FALSE, trimLogit = 0.001), cvControl = list(shuffle = FALSE))
    test.NNloglik3
    test.NNloglik3$control  # shows value of 0.001
    
    set.seed(1)
    test.NNloglik4 <- SuperLearner(Y = Y, X = X, SL.library = SL.library, method = "method.NNloglik", family = binomial(), control = list(saveFitLibrary = FALSE, trimLogit = 0.00001), cvControl = list(shuffle = FALSE))
    test.NNloglik4
    test.NNloglik4$control  # shows value of 0.00001
    
    # should return error
    SuperLearner(Y = Y, X = X, SL.library = SL.library, method = "method.NNloglik", family = binomial(), control = list(saveFitLibrary = FALSE, trimLogit = 0), cvControl = list(shuffle = FALSE))

**Comment by ck37** [comment]
Whoops, sorry about that - I should have tried the normal SuperLearner version instead of going directly to the intermediate functions.
