### ISSUE TITLE
SL.gam produces warnings on CRAN

### ISSUE THREAD

**Issue by benkeser** [ecpolley/SuperLearner#110]
I'm getting a warning from CRAN with the `drtmle` package ([see here](https://cran.r-project.org/web/checks/check_results_drtmle.html)). 

I think in `SL.gam` you either want
``` 
pred <- stats::predict(fit.gam, newdata = newX, type = "response")
```
or
```
pred <- gam:::predict.gam(fit.gam, newdata = newX, type = "response")
```
instead of the current version 
```
pred <- gam::predict.gam(fit.gam, newdata = newX, type = "response")
```

**Comment by ecpolley** [comment]
in the gam package, they just updated the name of the S3 class to 'Gam', the version of SuperLearner on Github has a check in place now, and hope to send that over to CRAN tomorrow.

    if(packageVersion('gam') >= 1.15) {
      pred <- gam::predict.Gam(fit.gam, newdata = newX, type = "response") # updated gam class in version 1.15
    } else {
      pred <- gam::predict.gam(fit.gam, newdata = newX, type = "response")
    }

see https://cran.r-project.org/web/packages/gam/ChangeLog

**Comment by benkeser** [comment]
Thanks. Now that you mention it, I do remember getting an email about this. Sorry to bother.

**Comment by ecpolley** [comment]
No problem, thanks for checking on it, I'll send you a note when the update is on CRAN to see if that fixes the issue.
