### ISSUE TITLE
doMC in test-randomForest.R

### ISSUE THREAD

**Issue by ecpolley** [ecpolley/SuperLearner#114]
in the `test-randomForest.R` test script, it includes a test for the `mcSuperLearner` algorithm but is wrapped in a conditional to only run if using RStudio to avoid CRAN checks. CRAN checks just got smarter and is now picking this up. We should be able to add `doMC` to the suggested packages list, but wanted to check if we should make any changes to the test script as well.

**Comment by ecpolley** [comment]
commented out test for now to avoid removal from CRAN

**Comment by ck37** [comment]
Sounds good, yeah sorry for my lack of response here.
