### ISSUE TITLE
Superlearner very slow

### ISSUE THREAD

**Issue by xhw197** [ecpolley/SuperLearner#118]
Hi,

I am using Superlearner to build a predictive model. i have about 700,000 rows and 60 columns. But for some reason, it runs very slow. i am using a parallel computing with 24 cores. Does anyone have any idea to improve the speed? thank you!

**Comment by ecpolley** [comment]
Hi, The SuperLearner R package isn't optimized for very large datasets. A few options might be to subsample your dataset and train on a smaller sample size. Another option is to check out the H2O implementation by @ledell (http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/stacked-ensembles.html).
