### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by pspin1** [ecpolley/SuperLearner#125]
I noticed large performance discrepancies between SuperLearner and ranger when fitting a Random Forest model to a data frame with 1200 rows. The outcome is binary and the predictors include three continuous variables, one five-level factor variable, and one binary variable. 

SuperLearner takes approximately 13 seconds to fit a default model, whereas ranger fits the default in 0.2 seconds. 

This is not a big deal when running one model at a time. It became a major constraint when running a permutation test (999 'simulations') to estimate an empirical p-value for Gini Impurity.

**Comment by ck37** [comment]
There are two reasons for the differences: 1) SuperLearner is conducting cross-validation, ranger is not, 2) the SuperLearner SL.ranger wrapper uses only 1 thread by default, which can be changed by using create.Learner() (see e.g. https://github.com/ecpolley/SuperLearner/blob/master/vignettes/Guide-to-SuperLearner.Rmd#L292).

**Comment by pspin1** [comment]
Just looping back. This helped a lot, thank you. 

The following revision brought run time down to 1.1 seconds.

# Test $4 - SL Ranger with increased number of threads
learners = create.Learner("SL.ranger", params = list(num.threads = 4))

system.time({
  out.sl.r4 <- mcSuperLearner(Y = Y, X = X, family = family, method = method,
    SL.library = learners$names)
})
