### ISSUE TITLE
discrete SL + full-fit SL

### ISSUE THREAD

**Issue by rachaelvp** [ecpolley/SuperLearner#137]
1. Is there a way to specify as the metalearner the cross-validated selector, so I can specify an SL that is the discrete SL?
2. Is there a way to specify a SuperLearner that ensembles predictions from models trained on _all_ of the data? This SL still learns the weights/ensemble/coefficients from the cross-validated predictions. [update: or is this already the default behavior?]

**Comment by ecpolley** [comment]
For 1, yes, with a custom `method.*` function, you could specify the coefficients to be 1 for the algorithm with the minimum CV risk estimate and 0 for the others. Take a look at `method.template` for the structure of writing your own method wrapper.

For 2, This is what the `SuperLearner()` function does. The coefficients are trained in the cross-validation, and the final ensemble combines the coefficients with the estimates trained using all the data.

**Comment by ecpolley** [comment]
Example method over in the SuperLearnerExtra space: 
https://github.com/ecpolley/SuperLearnerExtra/blob/master/method/method.discreteSL.R
