### ISSUE TITLE
xgboost: use xgb.cv with early_stopping 

### ISSUE THREAD

**Issue by rdiaz02** [ecpolley/SuperLearner#147]
Hi, thanks a lot for SuperLearner!

I wonder if it is possible to leverage on `xgb.cv` to tune  `ntrees`  (`nrounds`  in xgboost doc) without doing an explicit grid search over a set of `ntrees`. 
One very nice thing of `xgb.cv`  is that, using `early_stopping_rounds` , we can stop the tunning of `ntrees`.  Thus, when doing a grid search over parameters, we would not need to search over `ntrees`: just pass a large enough value of `ntrees` and use `early_stopping_rounds` (an example of doing a grid search for other parameters using this approach in https://bradleyboehmke.github.io/HOML/gbm.html#xgb-tuning-strategy).

I have not found anything that does this with SuperLearner. I guess I would need to write my own, following the examples in https://github.com/ecpolley/SuperLearnerExtra/tree/master/SL (e.g., SL.gbmOOB). 

Am I missing something obvious?

**Comment by ck37** [comment]
Hello, I have a wrapper here that does that: https://github.com/ck37/ck37r/blob/master/R/sl_xgboost_cv.RCheers,Chris-ck.mobileOn Dec 9, 2023, at 9:57 AM, Ramon Diaz-Uriarte ***@***.***> wrote:﻿
Hi, thanks a lot for SuperLearner!
I wonder if it is possible to leverage on xgb.cv to tune  ntrees  (nrounds  in xgboost doc) without doing an explicit grid search over a set of ntrees.
One very nice thing of xgb.cv  is that, using early_stopping_rounds , we can stop the tunning of ntrees.  Thus, when doing a grid search over parameters, we would not need to search over ntrees: just pass a large enough value of ntrees and use early_stopping_rounds (an example of doing a grid search for other parameters using this approach in https://bradleyboehmke.github.io/HOML/gbm.html#xgb-tuning-strategy).
I have not found anything that does this with SuperLearner. I guess I would need to write my own, following the examples in https://github.com/ecpolley/SuperLearnerExtra/tree/master/SL (e.g., SL.gbmOOB).
Am I missing something obvious?

**Comment by rdiaz02** [comment]
Thanks a lot!!!

**Comment by rdiaz02** [comment]
Closing, since this was never a bug to begin with, and the wrapper by @ck37 worked perfectly (I've been happily using a modified version of it).
