### ISSUE TITLE
algorithm-specific variable selection

### ISSUE THREAD

**Issue by fabian-s** [ecpolley/SuperLearner#23]
What would be the best way to perform variable selection for each algorithm in the ensemble separately?

To make this more concrete: From the performance of the single algorithms in an application one of my students is working on we know that SVM seems to work best with variables X, Y, Z while the neural network performs best with variables Y, Z, W, V. 
Is it better 
- to write specific wrappers that include this prior knowledge or 
- to write wrappers that include the variable selection step?

Or is there another way to do this we haven't thought of?

**Comment by ledell** [comment]
Fabian,
Are you familiar with using screener wrapper functions in your SL library?  This would be the more appropriate place to introduce feature selection vs within the base learner prediction functions.  To use a particular screener with a base learner, create a library such as:  
`SL.library <- list(c("SL.svm", "screen.randomForest"), c("SL.nnet", "screen.glmnet"))`

Type ` listWrappers()` to view the available prediction wrappers and screener wrappers. 

You are probably going to get the best performance by including all the variables in the training set, and then letting the screen functions/algos do their own variable selection.  However, assuming this prior knowledge is very high quality and better than what a glm or RF can infer from the data, you can create custom screener wrappers that simply drop the columns you have decided are not useful to SVM or neural nets.

**Comment by fabian-s** [comment]
Thanks for pointing that out. 

Seems to me like the screening functions use marginal correlations or randomForest variable importance or the LASSO/ElasticNet etc. to select variables, though. 

I was asking whether/how it is possible to include variable selection optimized for a particular algorithm, i.e., *selection based on the performance of the algorithm itself* with a certain subset of inputs, instead of selection based on a marginal heuristic or the selection of a different algorithm.  

Thanks again for your quick reply, it seems to me like that variable selection step  should then be included in a `screen.nnet` or `screen.svm` function we'd write ourselves and then pair that with `SL.nnet` etc....? Or a `screen.use_these` function that just gets the prior info "use X, V, Z" as its argument. 

Next question (sorry....):   Is the only way to hand over arguments to the functions in `SL.library` to define a function for each particular argument value as in the example for SuperLearner below or is there a better way? I'm referring to this example:

```r
create.SL.knn <- function(k = c(20, 30)) {
  for(mm in seq(length(k))){
    eval(parse(text = paste('SL.knn.', k[mm], '<- function(..., k = ', k[mm],
      ') SL.knn(..., k = k)', sep = '')), envir = .GlobalEnv)
  }
  invisible(TRUE)
}
create.SL.knn(c(20, 30, 40, 50, 60, 70))

# library with screening
SL.library <- list(c("SL.glmnet", "All"), c("SL.glm", "screen.randomForest"),
  "SL.randomForest", "SL.knn", "SL.knn.20", "SL.knn.30", "SL.knn.40",
  "SL.knn.50", "SL.knn.60", "SL.knn.70", 
  c("SL.polymars", "screen.randomForest"))
```

**Comment by ecpolley** [comment]
If you have a data.frame with columns W, X, Y, and Z and you want to selectively use those variables in different algorithms, you can create simple screening functions to select the variables you want. For example:

```
screen.WXY <- function(Y, X, …) { 
   whichVariable <- colnames(X) %in% c("W", "X", "Y")
   return(whichVariable)
}

screen.XYZ <- function(Y, X, …) { 
   whichVariable <- colnames(X) %in% c("Z", "X", "Y")
   return(whichVariable)
}

SL.library <- list(c("SL.svm", "screen.WXY"), c("SL.nnet", "screen.XYZ"))
```

**Comment by fabian-s** [comment]
Right, thank you both for your feedback & for providing this great package :+1:

**Comment by ecpolley** [comment]
And to your second question, that is the best way to handle those multiple parameters with the current version.

**Comment by drag05** [comment]
Hi there, I wonder if is possible to get variable importance (similar to caret::varImp()) for each base learner used in  CV.SuperLearner's or SuperLearner's training session. Thank you!

**Comment by ecpolley** [comment]
Hi @drag05 Can you start a new Issues for these questions? See instructions here https://help.github.com/articles/creating-an-issue/

**Comment by drag05** [comment]
Hello again, My base learners overfit while training on snowSuperLearner (left panel):

![overfittrain](https://user-images.githubusercontent.com/39677929/40740784-be7c06c2-6417-11e8-9a2b-abda6ff10ff9.png)

but they behave decently on CV.SuperLearner with the same V:

![otherbaselearn_roc](https://user-images.githubusercontent.com/39677929/40740678-6dd94a0e-6417-11e8-98c5-a3922e5bab00.png)

The ROC curves on the right panel are the test curves. The ROC plots were obtained with:
```{r}
caTools::colAUC(train_bPreds, train_admit, plotROC = TRUE, alg = 'ROC')
```
The snowSuperLearner AUCs during training are:
```{r}
        SL.mean_All SL.ranger_All SL.kernelKnn_All SL.glmnet_All SL.ksvm_All SL.xgboost_All SuperLearner
0 vs. 1         0.5             1        0.7755462     0.8408279   0.8966513       0.998837    0.9933038
```
and during testing are:
```{r}
 SL.ranger_All SL.glmnet_All SL.ksvm_All SL.xgboost_All SuperLearner
0 vs. 1     0.7258322     0.7093229   0.7235318      0.6762154    0.7119321
```

What is happening and what should I do to prevent train overfit? 

Thank you!

**Comment by drag05** [comment]
Hi, sorry I haven't seen your response while editing my last question. I will try. Thank you!
