### ISSUE TITLE
Multicore `CV.SuperLearner` defaults to 2 cores

### ISSUE THREAD

**Issue by ledell** [ecpolley/SuperLearner#24]
Hey @ecpolley, what do you think about updating the multicore logic to use k cores (or rather, min(k, ncores)) for k-fold cross-validation in the `CV.SuperLearner` function?

I suspect that a lot of people won't think to set `options(mc.cores = detectCores())`, and will not be getting optimal performance from their `CV.SuperLearner` since `parallel::mcapply` [defaults to 2 cores](http://www.rdocumentation.org/packages/parallel/functions/mclapply).  

Another solution is to document the default setting in the description of the `parallel` argument of the `CV.SuperLearner` function.

**Comment by ecpolley** [comment]
My thought is to only add documentation in CV.SuperLearner about setting number of cores to be used, but keep the fallback to 2L. The alternative would be something like:

```r
if(is.null(options()$mc.cores)) {
  detectCores <- detectCores()
  options(mc.cores = ifelse(is.na(detectCores), 2L, min(V, detectCores)))
}
```

But I haven't tested this.

**Comment by ecpolley** [comment]
Thanks, I've added a comment in the help page for `CV.SuperLearner` regarding the default number of cores for `mclapply`.

**Comment by ck37** [comment]
Side note, but detectCores() will give you threads, not physical cores. RhpcBLASctl::get_num_cores() will give you physical cores though.
