### ISSUE TITLE
Summary metalearner weights in CV.SuperLearner

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#25]
It would be handy if summary(CV.SuperLearner) also reported the distribution of the meta-learner weights of the algorithms, in addition to the risk. E.g mean, SE, min, max - just like risk. Seems like it would be easy to implement. Has this been considered?

**Comment by ecpolley** [comment]
Didn't think to add it to `summary()` but you can already get the values with `coef()` and since it is usually not a large number of folds, might be better to see the values instead of summaries. But you are correct, this would be an easy change.

**Comment by ck37** [comment]
Yeah I realized I should just take a look myself, so here is the code I used:

```r
meta_weights = t(sapply(cv_sl_out$AllSL, FUN=function(sl) { coef(sl) } ))
meta_weights
colMeans(meta_weights)
apply(meta_weights, MARGIN=2, FUN=function(col) { sd(col) })
```

**Comment by ecpolley** [comment]
Can also use:

    heatmap(t(coef(cv_sl_out)), scale = "none")

for a visual summary and makes it easy to see if two algorithms are alternating their weights.

**Comment by ecpolley** [comment]
And your line:

    meta_weights = t(sapply(cv_sl_out$AllSL, FUN=function(sl) { coef(sl) } ))

can be replaced with:

    meta_weights = coef(cv_sl_out)

Do avoid the `sapply`

**Comment by ck37** [comment]
Handy tips, thanks :)
