### ISSUE TITLE
GBM implementation missing shrinkage hyperparameter

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#27]
Reviewing the SL.gbm wrapper, and it appears that the implementation is missing the shrinkage parameter. The shrinkage parameter is critical to adjust between under and overfitting; without allowing different shrinkage terms the GBM cannot be adequately tuned to a given problem. Some of the other tuning parameters are not essential (e.g. bag.fraction, minobspernode) but shrinkage really is needed.

As an example here is a Caret page that includes some GBM hyper parameter optimization: http://topepo.github.io/caret/training.html

Happy to submit a patch for this. I think it's also worth considering a lower default number of trees, as 10,000 is quite high.

Cheers,
Chris

**Comment by ecpolley** [comment]
Added shrinkage to `SL.gbm`. 

Thanks,
Eric

**Comment by ck37** [comment]
Awesome, thanks!
