### ISSUE TITLE
method.AUC optimization warning with 1 learner

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#29]
Hi,

I'm trying out method.AUC and wanted to note two items:

1. It seems to always give an optim error about use "Brent":

```{r}
Warning messages:
1: In optim(par = coef_init, fn = .cvRisk_AUC, Z = Z, Y = Y, folds = NULL,  :
  one-dimensional optimization by Nelder-Mead is unreliable:
use "Brent" or optimize() directly
```

I tried modifying method.AUC() and changing the optimization to "Brent" but then it wants bounds that are not -Inf, +Inf so I gave up.

2. If SL.mean is in the library I get an error about newX:

```{r}
Error in nrow(newX) : argument "newX" is missing, with no default
```
And a warning:
```{r}
Warning message:
In FUN(X[[i]], ...) :
  replacing failed screening algorithm, SL.mean , with All() in full data 
```
In my case I'm testing with just two learners in my library, SL.glmnet and SL.mean, but the result shows a single learner with name "SL.glmnet_SL.mean".

Are these items known / are there workarounds?

It also seems that the risk result I get is still basically the L2 risk rather than 1-AUC, unless they happen to be almost exactly the same in my dataset. Maybe I'm messing up something else though.

Thanks,
Chris

**Comment by ck37** [comment]
Update: it seems that if I modify the optim call to specify lower=0 and upper=1 and change the default optim_method to "Brent" I don't get the optim warning anymore (https://github.com/ecpolley/SuperLearner/blob/master/R/method.R#L266):

```{r}
method.AUC <- function(optim_method="Brent") {
# ...
res <- optim(par=coef_init, fn=.cvRisk_AUC, Z=Z, Y=Y, folds=NULL, method=optim_method, lower=0, upper=1)
```

I don't know how kosher this is though.

**Comment by ecpolley** [comment]
Hi Chris,

Do you have an example you can share? If I run the following code it works with R version 3.3 and SuperLearner version 2.0-20 (cvAUC version 1.1.0):

    library(SuperLearner)
    library(glmnet)
    library(cvAUC)

    set.seed(1)
    N <- 200
    X <- matrix(rnorm(N*10), N, 10)
    X <- as.data.frame(X)
    Y <- rbinom(N, 1, plogis(.2*X[, 1] + .1*X[, 2] - .2*X[, 3] + .1*X[, 3]*X[, 4] - .2*abs(X[, 4])))

    SL.library <- c("SL.glmnet", "SL.mean")
  
    test.AUC <- SuperLearner(Y = Y, X = X, SL.library = SL.library, verbose = TRUE, method = "method.AUC", family = binomial())
    test.AUC

    test.NNLS <- SuperLearner(Y = Y, X = X, SL.library = SL.library, verbose = TRUE, method = "method.NNLS", family = binomial())    
    test.NNLS

**Comment by ck37** [comment]
Thanks Eric. Ok, it appears that the "use Brent" warning happens whenever method.AUC is used with a single library. So with your test, changing SL.library to:
```{r}
SL.library <- c("SL.glmnet")
```
should reproduce the warning, which is due to method.AUC using Nelder-Mead by default. But I suppose with only a single library the user could make a wrapper to method.AUC and specify the Brent method; the Brent method only works with a single library though, so it can't be the default. Maybe method.AUC could check if only a single library is specified and change the default optimization method so that the user doesn't have to do so.

Still investigating why I'm getting the SL.mean issue - will try to get a reproducible example going or find out what I'm doing wrong.

**Comment by ecpolley** [comment]
Ah, That makes more sense now. I'm not too concerned about this case since the coefficient should be 1 when you only have a single algorithm in the library and it won't change the estimation of that single algorithm. I've been thinking about adding a warning for when the library has only a single algorithm as this isn't the design for `SuperLearner`.

**Comment by ck37** [comment]
Sounds fair. As a use case though, I am examining the variation in my point estimates, CIs, & risk estimates for Q & G as I start with a single model and then iteratively add one more model to my SL library until reaching my final library complexity.

**Comment by ecpolley** [comment]
In your case, you should either start with 2 algorithms, or you could also build in a check if the SL.library only has a single algorithm and then set the coefficient to 1 and avoid the optimization:


    method.AUC.1 <- function(optim_method="Nelder-Mead") {
    	# Contributed by Erin Ledell, adapted for single algorithm check
    	out <- list(
    		require = c('cvAUC', 'ROCR'),
    		computeCoef = function(Z, Y, libraryNames, obsWeights, control, verbose, ...) {
			.cvRisk_AUC <- function(par, Z, Y, folds=NULL){
				# Calculate cvRisk, which is 1-cvAUC (Rank Loss)
				# This is the loss function that gets fed into optim as the "fn" argument 
				# par is the weight/coef vector for the ensemble in Super Learner
				predictions <- crossprod(t(Z), par)  #cv predicted SL values
				cvRisk <- 1 - cvAUC::cvAUC(predictions=predictions, labels=Y, folds=folds)$cvAUC
				return(cvRisk)
			}
			coef_init <- rep(1/ncol(Z),ncol(Z))
			names(coef_init) <- libraryNames
			# optim function selects the value for par that minimizes cvRisk_AUC (aka Rank Loss)
        if(ncol(Z) == 1) {
          coef <- 1
        } else {			
            res <- optim(par=coef_init, fn=.cvRisk_AUC, Z=Z, Y=Y, folds=NULL, method=optim_method)
			coef <- res$par
        }
			auc <- apply(Z, 2, function(x) cvAUC::cvAUC(x, labels=Y)$cvAUC)
			cvRisk <- 1 - auc  # Rank Loss
			names(coef) <- libraryNames
			out <- list(cvRisk = cvRisk, coef = coef)
			return(out)
		},
		computePred = function(predY, coef, control, ...) {
			out <- crossprod(t(predY), coef)
			return(out)
		}
	)
	invisible(out)
    }

**Comment by alelizben** [comment]
Was there a conclusion to the error
Error in nrow(newX) : argument "newX" is missing, with no default
when combining SL.glmnet and SL.mean?
I am seeing the same issue

**Comment by ck37** [comment]
It was some error in my own code, I don't have it anymore though. If you want to post your code we could take a look - would be best to start a new issue for it.
