### ISSUE TITLE
Error with SL.xgboost

### ISSUE THREAD

**Issue by ecpolley** [ecpolley/SuperLearner#38]
@ck37 
When adding the new `SL.xgboost`, I get the following error when trying to include in a library:

    Error in UseMethod("predict") : 
      no applicable method for 'predict' applied to an object of class "xgb.Booster"
    In addition: Warning message:
    In FUN(X[[i]], ...) : Error in algorithm SL.xgboost 
      The Algorithm will be removed from the Super Learner (i.e. given weight 0) 

It appears the xgboost package doesn't export the predict.xgb.Booster function. Do you have any suggestions?

Thanks,
Eric

**Comment by ck37** [comment]
It looks like this change is why it does not find the predict method:
https://github.com/ecpolley/SuperLearner/commit/0d7b5cdb7c6d8ac5732ac961d7ae9c848cfb928f

I tried a few other ways to access it and this was the only way I could get it to work. But I am new to namespaces so I could be missing something easier.

**Comment by ck37** [comment]
Ok, it looks to me that this works and is more precise:
```{r}
importFrom("xgboost", "predict")
```

**Comment by ecpolley** [comment]
Thanks, that seems to work!
