### ISSUE TITLE
Superlearner algorithm -- the best parameters of base learner with cross-validation

### ISSUE THREAD

**Issue by bifeng** [ecpolley/SuperLearner#53]
Could you help me with this simple question?
the fist stage of SuperLearner,  using the cross-validation, we can get the best parameters of base learner,
(this stage, we use the prediction of cross-validation and real value to train the meta-learner (so, the parameter of meta-learner is determined, and will be used for second stage))
the second stage of SuperLearner, did we using this best parameters of base learner to train the whole training set?
(this stage, we use the prediction of base learner to train the meta-learner)
I can't get it. Thank you!

**Comment by ecpolley** [comment]
Each of the individual learners are estimated within cross-validation for estimating the meta-learner and then using the entire data set. The final super learner is the coefficients of the meta-learner combined with the individual predictions for the learners estimated using the entire set.
