### ISSUE TITLE
Removing default internal cross-validation for SL.rpart

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#54]
Looking at SL.rpart, it seems to me that there is no reason for the default number of internal cross-validations to be 10 rather than 1. It makes sense to do cross-validation of rpart when the tree will be pruned based on the results, but that happens in rpartPrune rather than rpart. So we're basically just spending 10x the time fitting SL.rpart for no benefit.

I think with some benchmarks and tests it will be clear that removing the default cross-validation is helpful for SL.rpart, and for SL.rpartPrune it makes sense to keep the current defaults.

Any other thoughts or objections to this?

**Comment by ecpolley** [comment]
No objections, I ran a few test examples to make sure the predictions are identical. 10L is the default value in `rpart` (`rpart.control` for details) and it looks like 0L is a reasonable value and might be better than 1L here.

Thanks!
