### ISSUE TITLE
CV.SuperLearner with validRows

### ISSUE THREAD

**Issue by benkeser** [ecpolley/SuperLearner#55]
Hi Eric, 
I am trying to use `CV.SuperLearner` but specifying the outer splits via `SuperLearner.CV.control$validRows`.  This throws an error -- I think because `CV.SuperLearner` uses `SuperLearner.CV.control$validRows` to do the outer splitting and then tries to use the same `SuperLearner.CV.control$validRows` to do the inner splitting in the calls to `SuperLearner` in `.crossValFun`.

Here's a short snippet that reproduces the error: 
```{r}
Y <- rnorm(100)
X <- data.frame(x1=rnorm(100), x2 = rnorm(100))
validRows <- split(sample(1:100), rep(1:20, length = 100))

CV.SuperLearner(Y=Y, X=X, V=20, cvControl = list(validRows = validRows, V=20), SL.library = c("SL.glm","SL.mean"))
```

The error is 
```{r}
Error in `[<-`(`*tmp*`, unlist(validRows, use.names = FALSE), , value = c(-0.0420176534372252,  : 
  subscript out of bounds
```
and it's thrown in the call to .crossValFun. Here's the result of `traceback()`: 
```{r}
4: SuperLearner(Y = cvOutcome, X = cvLearn, newX = cvValid, family = family, 
       SL.library = SL.library, method = method, id = cvId, verbose = verbose, 
       control = control, cvControl = cvControl, obsWeights = cvObsWeights)
3: FUN(X[[i]], ...)
2: lapply(folds, FUN = .crossValFun, Y = Y, dataX = X, family = family, 
       SL.library = SL.library, method = method, id = id, obsWeights = obsWeights, 
       verbose = verbose, control = control, cvControl = cvControl, 
       saveAll = saveAll)
1: CV.SuperLearner(Y = Y, X = X, V = 20, cvControl = list(validRows = validRows, 
       V = 20), SL.library = c("SL.glm", "SL.mean"))
```
You can see the problem by stepping through the internal call to `SuperLearner` and looking at the output of the line `cvControl <- do.call("SuperLearner.CV.control", cvControl)`. 

Perhaps adding a separate option for the outer and inner splittings would solve the problem? E.g. outer splitting could be list and inner splitting would be list of lists. 

Apologies if I've misunderstood the code -- if so, could you please advise as to how to specify outer splits manually? 

Best,
David

**Comment by ecpolley** [comment]
Hi David,

Sorry, this has been on my ToDo list for a while. Your suggestion is exactly what I'm thinking we need to do. Have an "outerCvControl" list containing the parameters for the top level cross-validation splits, and then an argument for the user to provide a list of cvControl lists, with length equal to the number of outer cross-validation folds. Since each outer cross-validation fold might not be equally sized, we can't use a common inner cvControl object if you are using validRows. The current code will try to use the same validRows for both outer and inner cross-validation. I'll see if I can put a patch together soon.

**Comment by ecpolley** [comment]
Hi David,

I just pushed an update to GitHub for `CV.SuperLearner`. You can now use `cvControl` for the outer cross-validation controls, and added a new argument, `innerCvControl` which can be a single list with `cvControl` options passed to all of the internal `SuperLearner` calls, or a list with `V` cvControl lists, one for each cross-validation split. With this update, the `V` argument in `cvControl` is redundant and will throw an error message if you try to include both `V` and `cvControl = list(V = x)` as arguments in the `CV.SuperLearner` call. The recommendation is to use the `cvControl`, but I left `V` in as an argument for now to avoid breaking too many things. Let me know if this works for your example.

Thanks,
Eric

**Comment by benkeser** [comment]
Hi Eric,

That's great -- thank you! I will try it out this weekend. 

Best,
David
