### ISSUE TITLE
SL.xgboost predict still broken

### ISSUE THREAD

**Issue by ledell** [ecpolley/SuperLearner#58]
Hey @ck37 @ecpolley -- I don't think the recent PR fixes the bug with `predict` and the xgboost wrapper.  Running the [test](https://github.com/ecpolley/SuperLearner/blob/master/tests/testthat/testXGBoost.R) (and also on my own code), I keep getting this error:

```
Error in UseMethod("predict") :
  no applicable method for 'predict' applied to an object of class "xgb.Booster"
```
I think the function is not getting exported properly.

**Comment by ecpolley** [comment]
What version of xgboost?

**Comment by ck37** [comment]
Yep my guess is that this is with an old version of XGBoost, since the version on CRAN is out of date and incompatible with current Github versions due to namespace changes. Does installing a more recent version resolve? XGBoost also requires a weirder approach to install a recent version:

```r
install.packages("xgboost", repos=c("http://dmlc.ml/drat/", getOption("repos")), type="source")
```

**Comment by ledell** [comment]
Thanks, that fixed the bug.  This was xgboost version 0.4-4 (2016-07-12).  Is there something we can do to enforce a version of a Suggested package (DESCRIPTION does in fact say xgboost (>= 0.6)) -- or maybe add a warning that the the package must be updated in order to work?

**Comment by ecpolley** [comment]
maybe we need to add the following to `SL.xgboost`:

    if(packageVersion("xgboost") < 0.6) stop("SL.xgboost requires xgboost version >= 0.6")

Looks like suggest packages doesn't check versions.

**Comment by ck37** [comment]
Yep that seems like a fair idea, and will help until the CRAN version is updated.

**Comment by ecpolley** [comment]
fixed

**Comment by ck37** [comment]
The CRAN version of xgboost is now updated, so everyone can easily have a compatible version now. https://cran.r-project.org/web/packages/xgboost/
