### ISSUE TITLE
SL.earth hyperparameter tunings

### ISSUE THREAD

**Issue by EastBayEv** [ecpolley/SuperLearner#77]
Dear SuperLearner team -- 

I noticed that the SL.earth wrapper could use a few additional hyperparameter tunings based on the earth help page but that are currently lacking in the SL wrapper, namely:

- minspan
- endspan
- pmethod
- ncross
- nfold

Is it possible to update the wrapper to include these functions? These hyperparameters might be useful for users who wish to adjust algorithm fit by adjusting 1) the number of data points before the first and after the last knot, 2) the number of observations between knots, and 3) specifications of the pruning method (with additional configurations via ncross and nfold). I am hoping to use create.Learner to optimize these hyperparameters but they are currently lacking. 

Thank you,
Evan Muzzall
UC Berkeley Social Sciences D-Lab

**Comment by ecpolley** [comment]
Sure, I added `method`, `ncross`, and `nfold`, but I don't see `minspan` and `endspan` as parameters for the default method in earth:

  > args(earth:::earth.default)
  function (x = stop("no 'x' argument"), y = stop("no 'y' argument"), 
    weights = NULL, wp = NULL, subset = NULL, na.action = na.fail, 
    pmethod = c("backward", "none", "exhaustive", "forward", 
        "seqrep", "cv"), keepxy = FALSE, trace = 0, glm = NULL, 
    degree = 1, nprune = NULL, nfold = 0, ncross = 1, stratify = TRUE, 
    varmod.method = "none", varmod.exponent = 1, varmod.conv = 1, 
    varmod.clamp = 0.1, varmod.minspan = -3, Scale.y = (NCOL(y) == 
        1), ...) 
  NULL

**Comment by EastBayEv** [comment]
Eric -- 

Thanks for adding these and for your prompt reply;  apologies for my delayed one (end of semester blues). 

`minspan` and `endspan` are indeed there (they both default to zero; setting both to one will consider all x values), for example: 

library(earth)
data(iris)
earth1 <- earth(iris$Sepal.Length ~ ., data=iris, 
                pmethod="cv", nfold=10, ncross=1,
                degree=1, nk=5, 
                minspan=1, endspan=1)
summary(earth1)
evimp(earth1)
plot(earth1)

Kind regards,
Evan

**Comment by ecpolley** [comment]
I see, these two parameters aren't part of the main `earth` function, but are passed to an internal `earth.fit` function. I've added them to the `SL.earth` wrapper with default values of zero.
