### ISSUE TITLE
tuning parameters for SL.xgboost

### ISSUE THREAD

**Issue by ecpolley** [ecpolley/SuperLearner#81]
@ck37 for the tuning parameters in `SL.xgboost`, should `minchildweight` actually be `min_child_weight`? This is how it is defined in the help documents, but I couldn't find where it appears in the code.

**Comment by ck37** [comment]
Yeah I think you're right, looking at ?xgboost::xgboost and http://xgboost.readthedocs.io/en/latest/parameter.html . I haven't modified that parameter yet so that could explain why I didn't notice it on my end.

**Comment by ecpolley** [comment]
I've updated the `SL.xgboost` function.
