### ISSUE TITLE
New CRAN release?

### ISSUE THREAD

**Issue by ck37** [ecpolley/SuperLearner#84]
How about putting together a new CRAN release sometime? It's been a good while since the last one. Happy to help with anything to make it happen -- I haven't released to CRAN before.

Thanks,
Chris

**Comment by ecpolley** [comment]
Does `R CMD CHECK --as-cran` pass on both R-current and R-devel? I haven't checked recently.

**Comment by ck37** [comment]
I think the only remaining item is to fix the new vignette from using 4 cores on CRAN - will get that working.

**Comment by ck37** [comment]
Ok, I think we're good to go. All of the current build failures are due to idiosyncratic issues with the build system. For Appveyor it would go to do to this cache fix once (set env variable, rebuild one build, then unset the env variable) which should get it back into shape for general testing: https://github.com/ecpolley/SuperLearner/pull/83#issuecomment-305272875

**Comment by ecpolley** [comment]
Thanks, do you know if Appveyor and travis-CI are set up to test reverse dependencies as well?

**Comment by ck37** [comment]
They can run anything we want, I think it would just be a little tricky for automatic reverse dependency checking because we probably don't want that to run on every commit or PR due to slowness. Or is that what you're thinking?

**Comment by ecpolley** [comment]
Maybe not every commit but would be good for CRAN pre-flight testing
