### ISSUE TITLE
SL.predict fails when one alg fails...

### ISSUE THREAD

**Issue by jlstiles** [ecpolley/SuperLearner#94]
Just as it took the entire math/philosophy world something like 15 years to realize their definition of a set failed miserably due to Russell's paradox, this bug has gone on way too long...

```r
# This should not happen with SL.predict with a failed algorithm

# set up easy regression data
X = rnorm(100)
Y = 5*X + rnorm(100) + 2
X = data.frame(X = X)

# set up bad algorithm
SL.nothing = function(x) {x}

# declare the library
SL.library = c("SL.glm", "SL.nothing")

# call superlearner with bad alg in library
fit = SuperLearner(Y, X, family = gaussian, SL.library = SL.library)

# SL.predict breaks
preds = fit$SL.predict[1:100]

# library.predict still fine
fit$library.predict

# work around
preds = fit$library.predict[,fit$coef != 0] %*% fit$coef[fit$coef != 0] 
if (length(fit$coef[fit$coef != 0]) == 1) {
  preds = fit$library.predict[,fit$coef != 0]
} else {
  preds = fit$library.predict[,fit$coef != 0] %*% fit$coef[fit$coef != 0]  
}

preds
```

**Comment by ecpolley** [comment]
If you add `drop = FALSE` it will work with only a single learner:

    preds = fit$library.predict[,fit$coef != 0, drop = FALSE] %*% fit$coef[fit$coef != 0, drop = FALSE]

but you are right, the issue will depend on the method used, but in `method.NNLS` in the `crossprod` we have `NA * 0 = NA` and I don't think `crossprod` has a `na.rm` option. I can test out what impact it would have if we still use the `crossprod` but subset to the non-zero columns.

**Comment by ck37** [comment]
Thanks for posting this bug Jonathan. Should be fixed in this pull request: https://github.com/ecpolley/SuperLearner/pull/96
