### ISSUE TITLE
Include HAL as an algorithm--it's ready!

### ISSUE THREAD

**Issue by jlstiles** [ecpolley/SuperLearner#95]
I have been using David's SL wrapper for hal that comes with his package:

if (!require(devtools)) install.packages(devtools)
devtools::install_github("benkeser/halplus")

It is a fabulous wrapper so maybe we can just include it with a warning in the vignette that one should time it first before putting it in the library. Anyway, I'm sure that HAL with screeners will also be excellent even if dimension is high.

**Comment by ck37** [comment]
Do you have a reason for adding the HAL wrapper to the SuperLearner package given that it's already part of the HAL package?

I think there is some benefit to keeping an algorithm's wrapper in its own package, in that the package maintainers can update the wrapper more easily and there is less overhead for the SuperLearner package.

**Comment by jlstiles** [comment]
yes, good point.
